contract('Factory', function(accounts) {

  // Show that a contract can be generated by the factory
  it("create a new contract", function(done) {

  Factory.new({from: accounts[0]}).then(

    function(factory) {

      factory.createContract(accounts[0],"some address").then(
        function(){
          return factory.getNumberOfContracts();
        }).then(
        function(number) {
          assert.equal(number, 1, "One contract should have been created");
          done();

        }).catch(done);
    }).catch(done);

  });

  // Attempt to get a generated contract to say hello
  it("test a generated contract", function() {
    return Factory.new({ from: accounts[0] })
      .then(function(factory) {
        factory.createContract(accounts[0], "descriptor text", { from: accounts[0] });
        return factory;
      }).then(function(factory){
        return factory.getContract(0,{ from: accounts[0] });
      }).then(function(address) {
        var crowdfund = Crowdfund.at(address);
        return crowdfund.greet.call();
      })
      .then(function(greeting) {
        assert.equal(greeting, "works", "Check that the contract can say hi");
      })
  });

});
